import React from 'react';
import Head from 'next/head'
import App from './App/App';

export default function Home() {
  return (
    <>
      <Head>
        <title>Finished List</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.cdnfonts.com/css/8bit-wonder" rel="stylesheet"></link>
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@200&display=swap" rel="stylesheet"></link>
      </Head>
      <App></App>
    </>
  )
}
