import React, { useEffect } from 'react';
import Head from 'next/head'
import Navbar from '../Components/Navbar/Navbar';
import HomeView from './Home';
import GlobalStyle from '../styles/globals.module.scss'

export default function Home() {
  return (
    <>
      <Head>
        <title>Finished List</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={GlobalStyle.home}>
        <HomeView/>
      </div>
    </>
  )
}
